### PR TITLE
为 react 版本增加 prepare 脚本和 babel 编译后的文件

### PR DESCRIPTION
**Pull request by dexteryy**
现在 npm 社区的主流实践是：源代码可以用 es6 来开发，但发布到 npm 的时候，一定要同时提供 babel  编译后的版本（用 [prepare 钩子脚本](
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare)的方式），确保能被绝大部分项目直接使用，而无需在这些项目中去编译

原因是：1. 很多服务器端项目使用的 node.js 版本不支持原生 es6。2. 很多客户端项目是基于 webpack + babel-loader 的，最佳实践是在编译时忽略 node_modules 的文件：

https://github.com/babel/babel-loader#babel-loader-is-slow

### CODE REVIEW

**Comment by dexteryy** [comment]
@dntzhang thx, 能发布一个新版本的 npm package 吗~ （记得先 npm install 安装 devDependencies）

**Comment by dntzhang** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 verbose npm-session b045cc45da9def80
5 verbose publish [ '.' ]
6 info lifecycle alloyfinger@0.1.9~prepublish: alloyfinger@0.1.9
7 silly lifecycle alloyfinger@0.1.9~prepublish: no script for prepublish, continuing
8 info lifecycle alloyfinger@0.1.9~prepare: alloyfinger@0.1.9
9 verbose lifecycle alloyfinger@0.1.9~prepare: unsafe-perm in lifecycle true
10 verbose lifecycle alloyfinger@0.1.9~prepare: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\dntzhang\AlloyFinger\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Users\dntzhang\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\dntzhang\AppData\Roaming\npm;C:\Users\dntzhang\AppData\Local\Yarn\bin
11 verbose lifecycle alloyfinger@0.1.9~prepare: CWD: .
12 silly lifecycle alloyfinger@0.1.9~prepare: Args: [ '/d /s /c', 'npm run build' ]
13 silly lifecycle alloyfinger@0.1.9~prepare: Returned: code: 1  signal: null
14 info lifecycle alloyfinger@0.1.9~prepare: Failed to exec prepare script
15 verbose stack Error: alloyfinger@0.1.9 prepare: `npm run build`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
15 verbose stack     at emitTwo (events.js:125:13)
15 verbose stack     at EventEmitter.emit (events.js:213:7)
15 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
15 verbose stack     at emitTwo (events.js:125:13)
15 verbose stack     at ChildProcess.emit (events.js:213:7)
15 verbose stack     at maybeClose (internal/child_process.js:887:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
16 verbose pkgid alloyfinger@0.1.9
17 verbose cwd C:\Users\dntzhang\AlloyFinger
18 verbose Windows_NT 10.0.14393
19 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
20 verbose node v8.1.0
21 verbose npm  v5.0.3
22 error code ELIFECYCLE
23 error errno 1
24 error alloyfinger@0.1.9 prepare: `npm run build`
24 error Exit status 1
25 error Failed at the alloyfinger@0.1.9 prepare script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]


发布上去~~

**Comment by dntzhang** [comment]
qq 20170701082610

**Comment by dexteryy** [comment]
@dntzhang 呃不好意思，确实没考虑到 windows 环境的支持…… 

建议试试微软新出的 [WSL（Windows Subsystem for Linux）](https://msdn.microsoft.com/en-us/commandline/wsl/about)，可以像类 unix 环境一样执行 bash 脚本

除了这个方法之外，就只能在项目里添加 node.js 脚本来实现这个 bash 脚本的功能了：

```bash
if [ -d dist ]; then rm -r dist; fi; npm run build:react
```

**Pull request merged**
